description: Curb Application Test Workflow
name: Curb App Test

auth_service: true

nodes:
  chain_id: testnet-1
  count: 2
  image: ghcr.io/calimero-network/merod:edge
  prefix: curb-node
steps:
  # Step 1: Install the Curb application
  - name: Install Curb Application
    type: install_application
    node: curb-node-1
    path: 'examples/curb-js/build/curb.wasm'
    dev: true
    outputs:
      app_id: applicationId

  # Step 2: Create a context for the Curb app
  - name: Create Curb Context
    type: create_context
    node: curb-node-1
    application_id: '{{app_id}}'
    params: '{"ownerUsername": "testuser", "defaultChannels": [{"name": "general"}], "isDMchat": false}'
    outputs:
      context_id: contextId
      member_public_key: memberPublicKey

  # Step 3: Wait for context creation and sync
  - name: Wait For Context Sync
    type: wait
    seconds: 1
stop_all_nodes: false
restart: true
wait_timeout: 60